[neuron]
num_neurons = 100
v_rest = 0.0
v_thresh = 40.0
tau = 10.0

[weights]
strength_e = 250.0
strength_i = 50.0
sigma_e = 10.0
sigma_i = 40.0

[simulation]
dt = 1.0
num_timesteps = 1000
background_strength = 0.0
first_pulse_strength = 50.0
second_pulse_strength = 50.0
stimulation_length = 100